"""your message

Revision ID: 292107de092e
Revises: 5796db2ad70e
Create Date: 2025-06-21 16:36:22.414647

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '292107de092e'
down_revision = '5796db2ad70e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'updated_at')
    # ### end Alembic commands ###
