"""Add body column to messages

Revision ID: 5796db2ad70e
Revises: ac9c86199daf
Create Date: 2025-06-21 16:03:07.749315

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5796db2ad70e'
down_revision = 'ac9c86199daf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('body', sa.String(), nullable=True))
    op.add_column('messages', sa.Column('username', sa.String(), nullable=True))
    op.add_column('messages', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'created_at')
    op.drop_column('messages', 'username')
    op.drop_column('messages', 'body')
    # ### end Alembic commands ###
